name: logincloud
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.2
  firebase_auth: ^0.8.4+5
  google_sign_in: ^4.0.1+3
  http: ^0.12.0+2
  mqtt_client: ^5.6.1
  percent_indicator: ^2.1.1+1
  bezier_chart: ^1.0.15
  fl_chart: ^0.3.3
  charts_flutter: ^0.8.1
  flutter_sparkline: ^0.1.0
  syncfusion_flutter_charts: ^17.3.26
  oscilloscope: ^0.0.3
  flutter_staggered_grid_view: ^0.3.0

  syncfusion_flutter_gauges: ^17.3.26-beta

  fluttertoast: ^3.1.3

  vector_math: ^2.0.8
  font_awesome_flutter: 8.4.0
  unicorndial: ^1.1.5



dev_dependencies:
  flutter_test:
    sdk: flutter


flutter:

  uses-material-design: true

  assets:
        - assets/images/

